/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.checker.email.otp.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.multi.factor.authentication.checker.email.otp.model.MFAEmailOTP;
import com.liferay.multi.factor.authentication.checker.email.otp.model.MFAEmailOTPModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MFAEmailOTP service. Represents a row in the &quot;MFAEmailOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>MFAEmailOTPModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MFAEmailOTPImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see MFAEmailOTPImpl
 * @generated
 */
@ProviderType
public class MFAEmailOTPModelImpl
	extends BaseModelImpl<MFAEmailOTP> implements MFAEmailOTPModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mfa email otp model instance should use the <code>MFAEmailOTP</code> interface instead.
	 */
	public static final String TABLE_NAME = "MFAEmailOTP";

	public static final Object[][] TABLE_COLUMNS = {
		{"mfaEmailOTPId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"emailAddress", Types.VARCHAR}, {"failedAttempts", Types.INTEGER},
		{"lastSuccessDate", Types.TIMESTAMP}, {"lastSuccessIP", Types.VARCHAR},
		{"lastFailDate", Types.TIMESTAMP}, {"lastFailIP", Types.VARCHAR},
		{"mfaCheckerName", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mfaEmailOTPId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("emailAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("failedAttempts", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("lastSuccessDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastSuccessIP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastFailDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastFailIP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mfaCheckerName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MFAEmailOTP (mfaEmailOTPId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,emailAddress VARCHAR(75) null,failedAttempts INTEGER,lastSuccessDate DATE null,lastSuccessIP VARCHAR(75) null,lastFailDate DATE null,lastFailIP VARCHAR(75) null,mfaCheckerName VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table MFAEmailOTP";

	public static final String ORDER_BY_JPQL =
		" ORDER BY mfaEmailOTP.mfaEmailOTPId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MFAEmailOTP.mfaEmailOTPId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long MFACHECKERNAME_COLUMN_BITMASK = 1L;

	public static final long USERID_COLUMN_BITMASK = 2L;

	public static final long MFAEMAILOTPID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public MFAEmailOTPModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _mfaEmailOTPId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMfaEmailOTPId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _mfaEmailOTPId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MFAEmailOTP.class;
	}

	@Override
	public String getModelClassName() {
		return MFAEmailOTP.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MFAEmailOTP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MFAEmailOTP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MFAEmailOTP, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((MFAEmailOTP)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MFAEmailOTP, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MFAEmailOTP, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MFAEmailOTP)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MFAEmailOTP, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MFAEmailOTP, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MFAEmailOTP, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MFAEmailOTP, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MFAEmailOTP, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<MFAEmailOTP, Object>>();
		Map<String, BiConsumer<MFAEmailOTP, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MFAEmailOTP, ?>>();

		attributeGetterFunctions.put(
			"mfaEmailOTPId", MFAEmailOTP::getMfaEmailOTPId);
		attributeSetterBiConsumers.put(
			"mfaEmailOTPId",
			(BiConsumer<MFAEmailOTP, Long>)MFAEmailOTP::setMfaEmailOTPId);
		attributeGetterFunctions.put("companyId", MFAEmailOTP::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<MFAEmailOTP, Long>)MFAEmailOTP::setCompanyId);
		attributeGetterFunctions.put("userId", MFAEmailOTP::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<MFAEmailOTP, Long>)MFAEmailOTP::setUserId);
		attributeGetterFunctions.put("userName", MFAEmailOTP::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<MFAEmailOTP, String>)MFAEmailOTP::setUserName);
		attributeGetterFunctions.put("createDate", MFAEmailOTP::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<MFAEmailOTP, Date>)MFAEmailOTP::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", MFAEmailOTP::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<MFAEmailOTP, Date>)MFAEmailOTP::setModifiedDate);
		attributeGetterFunctions.put(
			"emailAddress", MFAEmailOTP::getEmailAddress);
		attributeSetterBiConsumers.put(
			"emailAddress",
			(BiConsumer<MFAEmailOTP, String>)MFAEmailOTP::setEmailAddress);
		attributeGetterFunctions.put(
			"failedAttempts", MFAEmailOTP::getFailedAttempts);
		attributeSetterBiConsumers.put(
			"failedAttempts",
			(BiConsumer<MFAEmailOTP, Integer>)MFAEmailOTP::setFailedAttempts);
		attributeGetterFunctions.put(
			"lastSuccessDate", MFAEmailOTP::getLastSuccessDate);
		attributeSetterBiConsumers.put(
			"lastSuccessDate",
			(BiConsumer<MFAEmailOTP, Date>)MFAEmailOTP::setLastSuccessDate);
		attributeGetterFunctions.put(
			"lastSuccessIP", MFAEmailOTP::getLastSuccessIP);
		attributeSetterBiConsumers.put(
			"lastSuccessIP",
			(BiConsumer<MFAEmailOTP, String>)MFAEmailOTP::setLastSuccessIP);
		attributeGetterFunctions.put(
			"lastFailDate", MFAEmailOTP::getLastFailDate);
		attributeSetterBiConsumers.put(
			"lastFailDate",
			(BiConsumer<MFAEmailOTP, Date>)MFAEmailOTP::setLastFailDate);
		attributeGetterFunctions.put("lastFailIP", MFAEmailOTP::getLastFailIP);
		attributeSetterBiConsumers.put(
			"lastFailIP",
			(BiConsumer<MFAEmailOTP, String>)MFAEmailOTP::setLastFailIP);
		attributeGetterFunctions.put(
			"mfaCheckerName", MFAEmailOTP::getMfaCheckerName);
		attributeSetterBiConsumers.put(
			"mfaCheckerName",
			(BiConsumer<MFAEmailOTP, String>)MFAEmailOTP::setMfaCheckerName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMfaEmailOTPId() {
		return _mfaEmailOTPId;
	}

	@Override
	public void setMfaEmailOTPId(long mfaEmailOTPId) {
		_mfaEmailOTPId = mfaEmailOTPId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getEmailAddress() {
		if (_emailAddress == null) {
			return "";
		}
		else {
			return _emailAddress;
		}
	}

	@Override
	public void setEmailAddress(String emailAddress) {
		_emailAddress = emailAddress;
	}

	@Override
	public int getFailedAttempts() {
		return _failedAttempts;
	}

	@Override
	public void setFailedAttempts(int failedAttempts) {
		_failedAttempts = failedAttempts;
	}

	@Override
	public Date getLastSuccessDate() {
		return _lastSuccessDate;
	}

	@Override
	public void setLastSuccessDate(Date lastSuccessDate) {
		_lastSuccessDate = lastSuccessDate;
	}

	@Override
	public String getLastSuccessIP() {
		if (_lastSuccessIP == null) {
			return "";
		}
		else {
			return _lastSuccessIP;
		}
	}

	@Override
	public void setLastSuccessIP(String lastSuccessIP) {
		_lastSuccessIP = lastSuccessIP;
	}

	@Override
	public Date getLastFailDate() {
		return _lastFailDate;
	}

	@Override
	public void setLastFailDate(Date lastFailDate) {
		_lastFailDate = lastFailDate;
	}

	@Override
	public String getLastFailIP() {
		if (_lastFailIP == null) {
			return "";
		}
		else {
			return _lastFailIP;
		}
	}

	@Override
	public void setLastFailIP(String lastFailIP) {
		_lastFailIP = lastFailIP;
	}

	@Override
	public String getMfaCheckerName() {
		if (_mfaCheckerName == null) {
			return "";
		}
		else {
			return _mfaCheckerName;
		}
	}

	@Override
	public void setMfaCheckerName(String mfaCheckerName) {
		_columnBitmask |= MFACHECKERNAME_COLUMN_BITMASK;

		if (_originalMfaCheckerName == null) {
			_originalMfaCheckerName = _mfaCheckerName;
		}

		_mfaCheckerName = mfaCheckerName;
	}

	public String getOriginalMfaCheckerName() {
		return GetterUtil.getString(_originalMfaCheckerName);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MFAEmailOTP.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MFAEmailOTP toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MFAEmailOTP)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MFAEmailOTPImpl mfaEmailOTPImpl = new MFAEmailOTPImpl();

		mfaEmailOTPImpl.setMfaEmailOTPId(getMfaEmailOTPId());
		mfaEmailOTPImpl.setCompanyId(getCompanyId());
		mfaEmailOTPImpl.setUserId(getUserId());
		mfaEmailOTPImpl.setUserName(getUserName());
		mfaEmailOTPImpl.setCreateDate(getCreateDate());
		mfaEmailOTPImpl.setModifiedDate(getModifiedDate());
		mfaEmailOTPImpl.setEmailAddress(getEmailAddress());
		mfaEmailOTPImpl.setFailedAttempts(getFailedAttempts());
		mfaEmailOTPImpl.setLastSuccessDate(getLastSuccessDate());
		mfaEmailOTPImpl.setLastSuccessIP(getLastSuccessIP());
		mfaEmailOTPImpl.setLastFailDate(getLastFailDate());
		mfaEmailOTPImpl.setLastFailIP(getLastFailIP());
		mfaEmailOTPImpl.setMfaCheckerName(getMfaCheckerName());

		mfaEmailOTPImpl.resetOriginalValues();

		return mfaEmailOTPImpl;
	}

	@Override
	public int compareTo(MFAEmailOTP mfaEmailOTP) {
		long primaryKey = mfaEmailOTP.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MFAEmailOTP)) {
			return false;
		}

		MFAEmailOTP mfaEmailOTP = (MFAEmailOTP)obj;

		long primaryKey = mfaEmailOTP.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		MFAEmailOTPModelImpl mfaEmailOTPModelImpl = this;

		mfaEmailOTPModelImpl._originalUserId = mfaEmailOTPModelImpl._userId;

		mfaEmailOTPModelImpl._setOriginalUserId = false;

		mfaEmailOTPModelImpl._setModifiedDate = false;

		mfaEmailOTPModelImpl._originalMfaCheckerName =
			mfaEmailOTPModelImpl._mfaCheckerName;

		mfaEmailOTPModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MFAEmailOTP> toCacheModel() {
		MFAEmailOTPCacheModel mfaEmailOTPCacheModel =
			new MFAEmailOTPCacheModel();

		mfaEmailOTPCacheModel.mfaEmailOTPId = getMfaEmailOTPId();

		mfaEmailOTPCacheModel.companyId = getCompanyId();

		mfaEmailOTPCacheModel.userId = getUserId();

		mfaEmailOTPCacheModel.userName = getUserName();

		String userName = mfaEmailOTPCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			mfaEmailOTPCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			mfaEmailOTPCacheModel.createDate = createDate.getTime();
		}
		else {
			mfaEmailOTPCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			mfaEmailOTPCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			mfaEmailOTPCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		mfaEmailOTPCacheModel.emailAddress = getEmailAddress();

		String emailAddress = mfaEmailOTPCacheModel.emailAddress;

		if ((emailAddress != null) && (emailAddress.length() == 0)) {
			mfaEmailOTPCacheModel.emailAddress = null;
		}

		mfaEmailOTPCacheModel.failedAttempts = getFailedAttempts();

		Date lastSuccessDate = getLastSuccessDate();

		if (lastSuccessDate != null) {
			mfaEmailOTPCacheModel.lastSuccessDate = lastSuccessDate.getTime();
		}
		else {
			mfaEmailOTPCacheModel.lastSuccessDate = Long.MIN_VALUE;
		}

		mfaEmailOTPCacheModel.lastSuccessIP = getLastSuccessIP();

		String lastSuccessIP = mfaEmailOTPCacheModel.lastSuccessIP;

		if ((lastSuccessIP != null) && (lastSuccessIP.length() == 0)) {
			mfaEmailOTPCacheModel.lastSuccessIP = null;
		}

		Date lastFailDate = getLastFailDate();

		if (lastFailDate != null) {
			mfaEmailOTPCacheModel.lastFailDate = lastFailDate.getTime();
		}
		else {
			mfaEmailOTPCacheModel.lastFailDate = Long.MIN_VALUE;
		}

		mfaEmailOTPCacheModel.lastFailIP = getLastFailIP();

		String lastFailIP = mfaEmailOTPCacheModel.lastFailIP;

		if ((lastFailIP != null) && (lastFailIP.length() == 0)) {
			mfaEmailOTPCacheModel.lastFailIP = null;
		}

		mfaEmailOTPCacheModel.mfaCheckerName = getMfaCheckerName();

		String mfaCheckerName = mfaEmailOTPCacheModel.mfaCheckerName;

		if ((mfaCheckerName != null) && (mfaCheckerName.length() == 0)) {
			mfaEmailOTPCacheModel.mfaCheckerName = null;
		}

		return mfaEmailOTPCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MFAEmailOTP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MFAEmailOTP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MFAEmailOTP, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((MFAEmailOTP)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MFAEmailOTP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MFAEmailOTP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MFAEmailOTP, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MFAEmailOTP)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		MFAEmailOTP.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		MFAEmailOTP.class, ModelWrapper.class
	};
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mfaEmailOTPId;
	private long _companyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _emailAddress;
	private int _failedAttempts;
	private Date _lastSuccessDate;
	private String _lastSuccessIP;
	private Date _lastFailDate;
	private String _lastFailIP;
	private String _mfaCheckerName;
	private String _originalMfaCheckerName;
	private long _columnBitmask;
	private MFAEmailOTP _escapedModel;

}