/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.checker.email.otp.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.multi.factor.authentication.checker.email.otp.model.MFAEmailOTP;
import com.liferay.multi.factor.authentication.checker.email.otp.service.MFAEmailOTPLocalServiceUtil;

/**
 * The extended model base implementation for the MFAEmailOTP service. Represents a row in the &quot;MFAEmailOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MFAEmailOTPImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see MFAEmailOTPImpl
 * @see MFAEmailOTP
 * @generated
 */
@ProviderType
public abstract class MFAEmailOTPBaseImpl
	extends MFAEmailOTPModelImpl implements MFAEmailOTP {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mfa email otp model instance should use the <code>MFAEmailOTP</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			MFAEmailOTPLocalServiceUtil.addMFAEmailOTP(this);
		}
		else {
			MFAEmailOTPLocalServiceUtil.updateMFAEmailOTP(this);
		}
	}

}