/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.checker.totp.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.multi.factor.authentication.checker.totp.model.MFATOTP;
import com.liferay.multi.factor.authentication.checker.totp.model.MFATOTPModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MFATOTP service. Represents a row in the &quot;MFATOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>MFATOTPModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MFATOTPImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see MFATOTPImpl
 * @generated
 */
@ProviderType
public class MFATOTPModelImpl
	extends BaseModelImpl<MFATOTP> implements MFATOTPModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a mfatotp model instance should use the <code>MFATOTP</code> interface instead.
	 */
	public static final String TABLE_NAME = "MFATOTP";

	public static final Object[][] TABLE_COLUMNS = {
		{"mfaTOTPId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"backupCodes", Types.VARCHAR}, {"failedLoginAttempts", Types.INTEGER},
		{"lastLoginDate", Types.TIMESTAMP}, {"lastLoginIP", Types.VARCHAR},
		{"lastFailedLoginDate", Types.TIMESTAMP},
		{"mfaCheckerName", Types.VARCHAR}, {"sharedSecret", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mfaTOTPId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("backupCodes", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("failedLoginAttempts", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("lastLoginDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastLoginIP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastFailedLoginDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("mfaCheckerName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sharedSecret", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MFATOTP (mfaTOTPId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,backupCodes VARCHAR(75) null,failedLoginAttempts INTEGER,lastLoginDate DATE null,lastLoginIP VARCHAR(75) null,lastFailedLoginDate DATE null,mfaCheckerName VARCHAR(75) null,sharedSecret VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table MFATOTP";

	public static final String ORDER_BY_JPQL =
		" ORDER BY mfatotp.mfaTOTPId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY MFATOTP.mfaTOTPId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long MFACHECKERNAME_COLUMN_BITMASK = 1L;

	public static final long USERID_COLUMN_BITMASK = 2L;

	public static final long MFATOTPID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public MFATOTPModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _mfaTOTPId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMfaTOTPId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _mfaTOTPId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MFATOTP.class;
	}

	@Override
	public String getModelClassName() {
		return MFATOTP.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MFATOTP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MFATOTP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MFATOTP, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((MFATOTP)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MFATOTP, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MFATOTP, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MFATOTP)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MFATOTP, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MFATOTP, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<MFATOTP, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MFATOTP, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<MFATOTP, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<MFATOTP, Object>>();
		Map<String, BiConsumer<MFATOTP, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MFATOTP, ?>>();

		attributeGetterFunctions.put("mfaTOTPId", MFATOTP::getMfaTOTPId);
		attributeSetterBiConsumers.put(
			"mfaTOTPId", (BiConsumer<MFATOTP, Long>)MFATOTP::setMfaTOTPId);
		attributeGetterFunctions.put("companyId", MFATOTP::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<MFATOTP, Long>)MFATOTP::setCompanyId);
		attributeGetterFunctions.put("userId", MFATOTP::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<MFATOTP, Long>)MFATOTP::setUserId);
		attributeGetterFunctions.put("userName", MFATOTP::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<MFATOTP, String>)MFATOTP::setUserName);
		attributeGetterFunctions.put("createDate", MFATOTP::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<MFATOTP, Date>)MFATOTP::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", MFATOTP::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<MFATOTP, Date>)MFATOTP::setModifiedDate);
		attributeGetterFunctions.put("backupCodes", MFATOTP::getBackupCodes);
		attributeSetterBiConsumers.put(
			"backupCodes",
			(BiConsumer<MFATOTP, String>)MFATOTP::setBackupCodes);
		attributeGetterFunctions.put(
			"failedLoginAttempts", MFATOTP::getFailedLoginAttempts);
		attributeSetterBiConsumers.put(
			"failedLoginAttempts",
			(BiConsumer<MFATOTP, Integer>)MFATOTP::setFailedLoginAttempts);
		attributeGetterFunctions.put(
			"lastLoginDate", MFATOTP::getLastLoginDate);
		attributeSetterBiConsumers.put(
			"lastLoginDate",
			(BiConsumer<MFATOTP, Date>)MFATOTP::setLastLoginDate);
		attributeGetterFunctions.put("lastLoginIP", MFATOTP::getLastLoginIP);
		attributeSetterBiConsumers.put(
			"lastLoginIP",
			(BiConsumer<MFATOTP, String>)MFATOTP::setLastLoginIP);
		attributeGetterFunctions.put(
			"lastFailedLoginDate", MFATOTP::getLastFailedLoginDate);
		attributeSetterBiConsumers.put(
			"lastFailedLoginDate",
			(BiConsumer<MFATOTP, Date>)MFATOTP::setLastFailedLoginDate);
		attributeGetterFunctions.put(
			"mfaCheckerName", MFATOTP::getMfaCheckerName);
		attributeSetterBiConsumers.put(
			"mfaCheckerName",
			(BiConsumer<MFATOTP, String>)MFATOTP::setMfaCheckerName);
		attributeGetterFunctions.put("sharedSecret", MFATOTP::getSharedSecret);
		attributeSetterBiConsumers.put(
			"sharedSecret",
			(BiConsumer<MFATOTP, String>)MFATOTP::setSharedSecret);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMfaTOTPId() {
		return _mfaTOTPId;
	}

	@Override
	public void setMfaTOTPId(long mfaTOTPId) {
		_mfaTOTPId = mfaTOTPId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getBackupCodes() {
		if (_backupCodes == null) {
			return "";
		}
		else {
			return _backupCodes;
		}
	}

	@Override
	public void setBackupCodes(String backupCodes) {
		_backupCodes = backupCodes;
	}

	@Override
	public int getFailedLoginAttempts() {
		return _failedLoginAttempts;
	}

	@Override
	public void setFailedLoginAttempts(int failedLoginAttempts) {
		_failedLoginAttempts = failedLoginAttempts;
	}

	@Override
	public Date getLastLoginDate() {
		return _lastLoginDate;
	}

	@Override
	public void setLastLoginDate(Date lastLoginDate) {
		_lastLoginDate = lastLoginDate;
	}

	@Override
	public String getLastLoginIP() {
		if (_lastLoginIP == null) {
			return "";
		}
		else {
			return _lastLoginIP;
		}
	}

	@Override
	public void setLastLoginIP(String lastLoginIP) {
		_lastLoginIP = lastLoginIP;
	}

	@Override
	public Date getLastFailedLoginDate() {
		return _lastFailedLoginDate;
	}

	@Override
	public void setLastFailedLoginDate(Date lastFailedLoginDate) {
		_lastFailedLoginDate = lastFailedLoginDate;
	}

	@Override
	public String getMfaCheckerName() {
		if (_mfaCheckerName == null) {
			return "";
		}
		else {
			return _mfaCheckerName;
		}
	}

	@Override
	public void setMfaCheckerName(String mfaCheckerName) {
		_columnBitmask |= MFACHECKERNAME_COLUMN_BITMASK;

		if (_originalMfaCheckerName == null) {
			_originalMfaCheckerName = _mfaCheckerName;
		}

		_mfaCheckerName = mfaCheckerName;
	}

	public String getOriginalMfaCheckerName() {
		return GetterUtil.getString(_originalMfaCheckerName);
	}

	@Override
	public String getSharedSecret() {
		if (_sharedSecret == null) {
			return "";
		}
		else {
			return _sharedSecret;
		}
	}

	@Override
	public void setSharedSecret(String sharedSecret) {
		_sharedSecret = sharedSecret;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MFATOTP.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MFATOTP toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MFATOTP)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MFATOTPImpl mfatotpImpl = new MFATOTPImpl();

		mfatotpImpl.setMfaTOTPId(getMfaTOTPId());
		mfatotpImpl.setCompanyId(getCompanyId());
		mfatotpImpl.setUserId(getUserId());
		mfatotpImpl.setUserName(getUserName());
		mfatotpImpl.setCreateDate(getCreateDate());
		mfatotpImpl.setModifiedDate(getModifiedDate());
		mfatotpImpl.setBackupCodes(getBackupCodes());
		mfatotpImpl.setFailedLoginAttempts(getFailedLoginAttempts());
		mfatotpImpl.setLastLoginDate(getLastLoginDate());
		mfatotpImpl.setLastLoginIP(getLastLoginIP());
		mfatotpImpl.setLastFailedLoginDate(getLastFailedLoginDate());
		mfatotpImpl.setMfaCheckerName(getMfaCheckerName());
		mfatotpImpl.setSharedSecret(getSharedSecret());

		mfatotpImpl.resetOriginalValues();

		return mfatotpImpl;
	}

	@Override
	public int compareTo(MFATOTP mfatotp) {
		long primaryKey = mfatotp.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MFATOTP)) {
			return false;
		}

		MFATOTP mfatotp = (MFATOTP)obj;

		long primaryKey = mfatotp.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		MFATOTPModelImpl mfatotpModelImpl = this;

		mfatotpModelImpl._originalUserId = mfatotpModelImpl._userId;

		mfatotpModelImpl._setOriginalUserId = false;

		mfatotpModelImpl._setModifiedDate = false;

		mfatotpModelImpl._originalMfaCheckerName =
			mfatotpModelImpl._mfaCheckerName;

		mfatotpModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MFATOTP> toCacheModel() {
		MFATOTPCacheModel mfatotpCacheModel = new MFATOTPCacheModel();

		mfatotpCacheModel.mfaTOTPId = getMfaTOTPId();

		mfatotpCacheModel.companyId = getCompanyId();

		mfatotpCacheModel.userId = getUserId();

		mfatotpCacheModel.userName = getUserName();

		String userName = mfatotpCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			mfatotpCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			mfatotpCacheModel.createDate = createDate.getTime();
		}
		else {
			mfatotpCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			mfatotpCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			mfatotpCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		mfatotpCacheModel.backupCodes = getBackupCodes();

		String backupCodes = mfatotpCacheModel.backupCodes;

		if ((backupCodes != null) && (backupCodes.length() == 0)) {
			mfatotpCacheModel.backupCodes = null;
		}

		mfatotpCacheModel.failedLoginAttempts = getFailedLoginAttempts();

		Date lastLoginDate = getLastLoginDate();

		if (lastLoginDate != null) {
			mfatotpCacheModel.lastLoginDate = lastLoginDate.getTime();
		}
		else {
			mfatotpCacheModel.lastLoginDate = Long.MIN_VALUE;
		}

		mfatotpCacheModel.lastLoginIP = getLastLoginIP();

		String lastLoginIP = mfatotpCacheModel.lastLoginIP;

		if ((lastLoginIP != null) && (lastLoginIP.length() == 0)) {
			mfatotpCacheModel.lastLoginIP = null;
		}

		Date lastFailedLoginDate = getLastFailedLoginDate();

		if (lastFailedLoginDate != null) {
			mfatotpCacheModel.lastFailedLoginDate =
				lastFailedLoginDate.getTime();
		}
		else {
			mfatotpCacheModel.lastFailedLoginDate = Long.MIN_VALUE;
		}

		mfatotpCacheModel.mfaCheckerName = getMfaCheckerName();

		String mfaCheckerName = mfatotpCacheModel.mfaCheckerName;

		if ((mfaCheckerName != null) && (mfaCheckerName.length() == 0)) {
			mfatotpCacheModel.mfaCheckerName = null;
		}

		mfatotpCacheModel.sharedSecret = getSharedSecret();

		String sharedSecret = mfatotpCacheModel.sharedSecret;

		if ((sharedSecret != null) && (sharedSecret.length() == 0)) {
			mfatotpCacheModel.sharedSecret = null;
		}

		return mfatotpCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MFATOTP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MFATOTP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MFATOTP, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((MFATOTP)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MFATOTP, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MFATOTP, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MFATOTP, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MFATOTP)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		MFATOTP.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		MFATOTP.class, ModelWrapper.class
	};
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mfaTOTPId;
	private long _companyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _backupCodes;
	private int _failedLoginAttempts;
	private Date _lastLoginDate;
	private String _lastLoginIP;
	private Date _lastFailedLoginDate;
	private String _mfaCheckerName;
	private String _originalMfaCheckerName;
	private String _sharedSecret;
	private long _columnBitmask;
	private MFATOTP _escapedModel;

}