/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.checker.email.otp.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

/**
 * The base model interface for the MFAEmailOTP service. Represents a row in the &quot;MFAEmailOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.multi.factor.authentication.checker.email.otp.model.impl.MFAEmailOTPModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.multi.factor.authentication.checker.email.otp.model.impl.MFAEmailOTPImpl</code>.
 * </p>
 *
 * @author arthurchan35
 * @see MFAEmailOTP
 * @generated
 */
@ProviderType
public interface MFAEmailOTPModel
	extends AuditedModel, BaseModel<MFAEmailOTP>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mfa email otp model instance should use the {@link MFAEmailOTP} interface instead.
	 */

	/**
	 * Returns the primary key of this mfa email otp.
	 *
	 * @return the primary key of this mfa email otp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mfa email otp.
	 *
	 * @param primaryKey the primary key of this mfa email otp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mfa email otp ID of this mfa email otp.
	 *
	 * @return the mfa email otp ID of this mfa email otp
	 */
	public long getMfaEmailOTPId();

	/**
	 * Sets the mfa email otp ID of this mfa email otp.
	 *
	 * @param mfaEmailOTPId the mfa email otp ID of this mfa email otp
	 */
	public void setMfaEmailOTPId(long mfaEmailOTPId);

	/**
	 * Returns the company ID of this mfa email otp.
	 *
	 * @return the company ID of this mfa email otp
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this mfa email otp.
	 *
	 * @param companyId the company ID of this mfa email otp
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this mfa email otp.
	 *
	 * @return the user ID of this mfa email otp
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this mfa email otp.
	 *
	 * @param userId the user ID of this mfa email otp
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this mfa email otp.
	 *
	 * @return the user uuid of this mfa email otp
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this mfa email otp.
	 *
	 * @param userUuid the user uuid of this mfa email otp
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this mfa email otp.
	 *
	 * @return the user name of this mfa email otp
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this mfa email otp.
	 *
	 * @param userName the user name of this mfa email otp
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this mfa email otp.
	 *
	 * @return the create date of this mfa email otp
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this mfa email otp.
	 *
	 * @param createDate the create date of this mfa email otp
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this mfa email otp.
	 *
	 * @return the modified date of this mfa email otp
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this mfa email otp.
	 *
	 * @param modifiedDate the modified date of this mfa email otp
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the email address of this mfa email otp.
	 *
	 * @return the email address of this mfa email otp
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this mfa email otp.
	 *
	 * @param emailAddress the email address of this mfa email otp
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Returns the failed attempts of this mfa email otp.
	 *
	 * @return the failed attempts of this mfa email otp
	 */
	public int getFailedAttempts();

	/**
	 * Sets the failed attempts of this mfa email otp.
	 *
	 * @param failedAttempts the failed attempts of this mfa email otp
	 */
	public void setFailedAttempts(int failedAttempts);

	/**
	 * Returns the last success date of this mfa email otp.
	 *
	 * @return the last success date of this mfa email otp
	 */
	public Date getLastSuccessDate();

	/**
	 * Sets the last success date of this mfa email otp.
	 *
	 * @param lastSuccessDate the last success date of this mfa email otp
	 */
	public void setLastSuccessDate(Date lastSuccessDate);

	/**
	 * Returns the last success ip of this mfa email otp.
	 *
	 * @return the last success ip of this mfa email otp
	 */
	@AutoEscape
	public String getLastSuccessIP();

	/**
	 * Sets the last success ip of this mfa email otp.
	 *
	 * @param lastSuccessIP the last success ip of this mfa email otp
	 */
	public void setLastSuccessIP(String lastSuccessIP);

	/**
	 * Returns the last fail date of this mfa email otp.
	 *
	 * @return the last fail date of this mfa email otp
	 */
	public Date getLastFailDate();

	/**
	 * Sets the last fail date of this mfa email otp.
	 *
	 * @param lastFailDate the last fail date of this mfa email otp
	 */
	public void setLastFailDate(Date lastFailDate);

	/**
	 * Returns the last fail ip of this mfa email otp.
	 *
	 * @return the last fail ip of this mfa email otp
	 */
	@AutoEscape
	public String getLastFailIP();

	/**
	 * Sets the last fail ip of this mfa email otp.
	 *
	 * @param lastFailIP the last fail ip of this mfa email otp
	 */
	public void setLastFailIP(String lastFailIP);

	/**
	 * Returns the mfa checker name of this mfa email otp.
	 *
	 * @return the mfa checker name of this mfa email otp
	 */
	@AutoEscape
	public String getMfaCheckerName();

	/**
	 * Sets the mfa checker name of this mfa email otp.
	 *
	 * @param mfaCheckerName the mfa checker name of this mfa email otp
	 */
	public void setMfaCheckerName(String mfaCheckerName);

}