/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.checker.totp.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

/**
 * The base model interface for the MFATOTP service. Represents a row in the &quot;MFATOTP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.multi.factor.authentication.checker.totp.model.impl.MFATOTPModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.multi.factor.authentication.checker.totp.model.impl.MFATOTPImpl</code>.
 * </p>
 *
 * @author arthurchan35
 * @see MFATOTP
 * @generated
 */
@ProviderType
public interface MFATOTPModel
	extends AuditedModel, BaseModel<MFATOTP>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mfatotp model instance should use the {@link MFATOTP} interface instead.
	 */

	/**
	 * Returns the primary key of this mfatotp.
	 *
	 * @return the primary key of this mfatotp
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this mfatotp.
	 *
	 * @param primaryKey the primary key of this mfatotp
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mfa totp ID of this mfatotp.
	 *
	 * @return the mfa totp ID of this mfatotp
	 */
	public long getMfaTOTPId();

	/**
	 * Sets the mfa totp ID of this mfatotp.
	 *
	 * @param mfaTOTPId the mfa totp ID of this mfatotp
	 */
	public void setMfaTOTPId(long mfaTOTPId);

	/**
	 * Returns the company ID of this mfatotp.
	 *
	 * @return the company ID of this mfatotp
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this mfatotp.
	 *
	 * @param companyId the company ID of this mfatotp
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this mfatotp.
	 *
	 * @return the user ID of this mfatotp
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this mfatotp.
	 *
	 * @param userId the user ID of this mfatotp
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this mfatotp.
	 *
	 * @return the user uuid of this mfatotp
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this mfatotp.
	 *
	 * @param userUuid the user uuid of this mfatotp
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this mfatotp.
	 *
	 * @return the user name of this mfatotp
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this mfatotp.
	 *
	 * @param userName the user name of this mfatotp
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this mfatotp.
	 *
	 * @return the create date of this mfatotp
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this mfatotp.
	 *
	 * @param createDate the create date of this mfatotp
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this mfatotp.
	 *
	 * @return the modified date of this mfatotp
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this mfatotp.
	 *
	 * @param modifiedDate the modified date of this mfatotp
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the backup codes of this mfatotp.
	 *
	 * @return the backup codes of this mfatotp
	 */
	@AutoEscape
	public String getBackupCodes();

	/**
	 * Sets the backup codes of this mfatotp.
	 *
	 * @param backupCodes the backup codes of this mfatotp
	 */
	public void setBackupCodes(String backupCodes);

	/**
	 * Returns the failed login attempts of this mfatotp.
	 *
	 * @return the failed login attempts of this mfatotp
	 */
	public int getFailedLoginAttempts();

	/**
	 * Sets the failed login attempts of this mfatotp.
	 *
	 * @param failedLoginAttempts the failed login attempts of this mfatotp
	 */
	public void setFailedLoginAttempts(int failedLoginAttempts);

	/**
	 * Returns the last login date of this mfatotp.
	 *
	 * @return the last login date of this mfatotp
	 */
	public Date getLastLoginDate();

	/**
	 * Sets the last login date of this mfatotp.
	 *
	 * @param lastLoginDate the last login date of this mfatotp
	 */
	public void setLastLoginDate(Date lastLoginDate);

	/**
	 * Returns the last login ip of this mfatotp.
	 *
	 * @return the last login ip of this mfatotp
	 */
	@AutoEscape
	public String getLastLoginIP();

	/**
	 * Sets the last login ip of this mfatotp.
	 *
	 * @param lastLoginIP the last login ip of this mfatotp
	 */
	public void setLastLoginIP(String lastLoginIP);

	/**
	 * Returns the last failed login date of this mfatotp.
	 *
	 * @return the last failed login date of this mfatotp
	 */
	public Date getLastFailedLoginDate();

	/**
	 * Sets the last failed login date of this mfatotp.
	 *
	 * @param lastFailedLoginDate the last failed login date of this mfatotp
	 */
	public void setLastFailedLoginDate(Date lastFailedLoginDate);

	/**
	 * Returns the mfa checker name of this mfatotp.
	 *
	 * @return the mfa checker name of this mfatotp
	 */
	@AutoEscape
	public String getMfaCheckerName();

	/**
	 * Sets the mfa checker name of this mfatotp.
	 *
	 * @param mfaCheckerName the mfa checker name of this mfatotp
	 */
	public void setMfaCheckerName(String mfaCheckerName);

	/**
	 * Returns the shared secret of this mfatotp.
	 *
	 * @return the shared secret of this mfatotp
	 */
	@AutoEscape
	public String getSharedSecret();

	/**
	 * Sets the shared secret of this mfatotp.
	 *
	 * @param sharedSecret the shared secret of this mfatotp
	 */
	public void setSharedSecret(String sharedSecret);

}