/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.checker.timebased.otp.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.multi.factor.authentication.checker.timebased.otp.model.TimebasedOTPEntry;
import com.liferay.multi.factor.authentication.checker.timebased.otp.model.TimebasedOTPEntryModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TimebasedOTPEntry service. Represents a row in the &quot;MFATOTPEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>TimebasedOTPEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TimebasedOTPEntryImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see TimebasedOTPEntryImpl
 * @generated
 */
@ProviderType
public class TimebasedOTPEntryModelImpl
	extends BaseModelImpl<TimebasedOTPEntry> implements TimebasedOTPEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a timebased otp entry model instance should use the <code>TimebasedOTPEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "MFATOTPEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"entryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"failedAttempts", Types.INTEGER}, {"lastFailDate", Types.TIMESTAMP},
		{"lastFailIP", Types.VARCHAR}, {"lastSuccessDate", Types.TIMESTAMP},
		{"lastSuccessIP", Types.VARCHAR}, {"mfaCheckerName", Types.VARCHAR},
		{"sharedSecret", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("entryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("failedAttempts", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("lastFailDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastFailIP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastSuccessDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lastSuccessIP", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mfaCheckerName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sharedSecret", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MFATOTPEntry (entryId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,failedAttempts INTEGER,lastFailDate DATE null,lastFailIP VARCHAR(75) null,lastSuccessDate DATE null,lastSuccessIP VARCHAR(75) null,mfaCheckerName VARCHAR(75) null,sharedSecret VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table MFATOTPEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY timebasedOTPEntry.entryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MFATOTPEntry.entryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long MFACHECKERNAME_COLUMN_BITMASK = 1L;

	public static final long USERID_COLUMN_BITMASK = 2L;

	public static final long ENTRYID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public TimebasedOTPEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _entryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _entryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TimebasedOTPEntry.class;
	}

	@Override
	public String getModelClassName() {
		return TimebasedOTPEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TimebasedOTPEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TimebasedOTPEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TimebasedOTPEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TimebasedOTPEntry)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TimebasedOTPEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TimebasedOTPEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TimebasedOTPEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TimebasedOTPEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TimebasedOTPEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<TimebasedOTPEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<TimebasedOTPEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<TimebasedOTPEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<TimebasedOTPEntry, Object>>();
		Map<String, BiConsumer<TimebasedOTPEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<TimebasedOTPEntry, ?>>();

		attributeGetterFunctions.put("entryId", TimebasedOTPEntry::getEntryId);
		attributeSetterBiConsumers.put(
			"entryId",
			(BiConsumer<TimebasedOTPEntry, Long>)TimebasedOTPEntry::setEntryId);
		attributeGetterFunctions.put(
			"companyId", TimebasedOTPEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<TimebasedOTPEntry, Long>)
				TimebasedOTPEntry::setCompanyId);
		attributeGetterFunctions.put("userId", TimebasedOTPEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<TimebasedOTPEntry, Long>)TimebasedOTPEntry::setUserId);
		attributeGetterFunctions.put(
			"userName", TimebasedOTPEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<TimebasedOTPEntry, String>)
				TimebasedOTPEntry::setUserName);
		attributeGetterFunctions.put(
			"createDate", TimebasedOTPEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<TimebasedOTPEntry, Date>)
				TimebasedOTPEntry::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", TimebasedOTPEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<TimebasedOTPEntry, Date>)
				TimebasedOTPEntry::setModifiedDate);
		attributeGetterFunctions.put(
			"failedAttempts", TimebasedOTPEntry::getFailedAttempts);
		attributeSetterBiConsumers.put(
			"failedAttempts",
			(BiConsumer<TimebasedOTPEntry, Integer>)
				TimebasedOTPEntry::setFailedAttempts);
		attributeGetterFunctions.put(
			"lastFailDate", TimebasedOTPEntry::getLastFailDate);
		attributeSetterBiConsumers.put(
			"lastFailDate",
			(BiConsumer<TimebasedOTPEntry, Date>)
				TimebasedOTPEntry::setLastFailDate);
		attributeGetterFunctions.put(
			"lastFailIP", TimebasedOTPEntry::getLastFailIP);
		attributeSetterBiConsumers.put(
			"lastFailIP",
			(BiConsumer<TimebasedOTPEntry, String>)
				TimebasedOTPEntry::setLastFailIP);
		attributeGetterFunctions.put(
			"lastSuccessDate", TimebasedOTPEntry::getLastSuccessDate);
		attributeSetterBiConsumers.put(
			"lastSuccessDate",
			(BiConsumer<TimebasedOTPEntry, Date>)
				TimebasedOTPEntry::setLastSuccessDate);
		attributeGetterFunctions.put(
			"lastSuccessIP", TimebasedOTPEntry::getLastSuccessIP);
		attributeSetterBiConsumers.put(
			"lastSuccessIP",
			(BiConsumer<TimebasedOTPEntry, String>)
				TimebasedOTPEntry::setLastSuccessIP);
		attributeGetterFunctions.put(
			"mfaCheckerName", TimebasedOTPEntry::getMfaCheckerName);
		attributeSetterBiConsumers.put(
			"mfaCheckerName",
			(BiConsumer<TimebasedOTPEntry, String>)
				TimebasedOTPEntry::setMfaCheckerName);
		attributeGetterFunctions.put(
			"sharedSecret", TimebasedOTPEntry::getSharedSecret);
		attributeSetterBiConsumers.put(
			"sharedSecret",
			(BiConsumer<TimebasedOTPEntry, String>)
				TimebasedOTPEntry::setSharedSecret);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getEntryId() {
		return _entryId;
	}

	@Override
	public void setEntryId(long entryId) {
		_entryId = entryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public int getFailedAttempts() {
		return _failedAttempts;
	}

	@Override
	public void setFailedAttempts(int failedAttempts) {
		_failedAttempts = failedAttempts;
	}

	@Override
	public Date getLastFailDate() {
		return _lastFailDate;
	}

	@Override
	public void setLastFailDate(Date lastFailDate) {
		_lastFailDate = lastFailDate;
	}

	@Override
	public String getLastFailIP() {
		if (_lastFailIP == null) {
			return "";
		}
		else {
			return _lastFailIP;
		}
	}

	@Override
	public void setLastFailIP(String lastFailIP) {
		_lastFailIP = lastFailIP;
	}

	@Override
	public Date getLastSuccessDate() {
		return _lastSuccessDate;
	}

	@Override
	public void setLastSuccessDate(Date lastSuccessDate) {
		_lastSuccessDate = lastSuccessDate;
	}

	@Override
	public String getLastSuccessIP() {
		if (_lastSuccessIP == null) {
			return "";
		}
		else {
			return _lastSuccessIP;
		}
	}

	@Override
	public void setLastSuccessIP(String lastSuccessIP) {
		_lastSuccessIP = lastSuccessIP;
	}

	@Override
	public String getMfaCheckerName() {
		if (_mfaCheckerName == null) {
			return "";
		}
		else {
			return _mfaCheckerName;
		}
	}

	@Override
	public void setMfaCheckerName(String mfaCheckerName) {
		_columnBitmask |= MFACHECKERNAME_COLUMN_BITMASK;

		if (_originalMfaCheckerName == null) {
			_originalMfaCheckerName = _mfaCheckerName;
		}

		_mfaCheckerName = mfaCheckerName;
	}

	public String getOriginalMfaCheckerName() {
		return GetterUtil.getString(_originalMfaCheckerName);
	}

	@Override
	public String getSharedSecret() {
		if (_sharedSecret == null) {
			return "";
		}
		else {
			return _sharedSecret;
		}
	}

	@Override
	public void setSharedSecret(String sharedSecret) {
		_sharedSecret = sharedSecret;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TimebasedOTPEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TimebasedOTPEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TimebasedOTPEntry)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TimebasedOTPEntryImpl timebasedOTPEntryImpl =
			new TimebasedOTPEntryImpl();

		timebasedOTPEntryImpl.setEntryId(getEntryId());
		timebasedOTPEntryImpl.setCompanyId(getCompanyId());
		timebasedOTPEntryImpl.setUserId(getUserId());
		timebasedOTPEntryImpl.setUserName(getUserName());
		timebasedOTPEntryImpl.setCreateDate(getCreateDate());
		timebasedOTPEntryImpl.setModifiedDate(getModifiedDate());
		timebasedOTPEntryImpl.setFailedAttempts(getFailedAttempts());
		timebasedOTPEntryImpl.setLastFailDate(getLastFailDate());
		timebasedOTPEntryImpl.setLastFailIP(getLastFailIP());
		timebasedOTPEntryImpl.setLastSuccessDate(getLastSuccessDate());
		timebasedOTPEntryImpl.setLastSuccessIP(getLastSuccessIP());
		timebasedOTPEntryImpl.setMfaCheckerName(getMfaCheckerName());
		timebasedOTPEntryImpl.setSharedSecret(getSharedSecret());

		timebasedOTPEntryImpl.resetOriginalValues();

		return timebasedOTPEntryImpl;
	}

	@Override
	public int compareTo(TimebasedOTPEntry timebasedOTPEntry) {
		long primaryKey = timebasedOTPEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TimebasedOTPEntry)) {
			return false;
		}

		TimebasedOTPEntry timebasedOTPEntry = (TimebasedOTPEntry)obj;

		long primaryKey = timebasedOTPEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		TimebasedOTPEntryModelImpl timebasedOTPEntryModelImpl = this;

		timebasedOTPEntryModelImpl._originalUserId =
			timebasedOTPEntryModelImpl._userId;

		timebasedOTPEntryModelImpl._setOriginalUserId = false;

		timebasedOTPEntryModelImpl._setModifiedDate = false;

		timebasedOTPEntryModelImpl._originalMfaCheckerName =
			timebasedOTPEntryModelImpl._mfaCheckerName;

		timebasedOTPEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TimebasedOTPEntry> toCacheModel() {
		TimebasedOTPEntryCacheModel timebasedOTPEntryCacheModel =
			new TimebasedOTPEntryCacheModel();

		timebasedOTPEntryCacheModel.entryId = getEntryId();

		timebasedOTPEntryCacheModel.companyId = getCompanyId();

		timebasedOTPEntryCacheModel.userId = getUserId();

		timebasedOTPEntryCacheModel.userName = getUserName();

		String userName = timebasedOTPEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			timebasedOTPEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			timebasedOTPEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			timebasedOTPEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			timebasedOTPEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			timebasedOTPEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		timebasedOTPEntryCacheModel.failedAttempts = getFailedAttempts();

		Date lastFailDate = getLastFailDate();

		if (lastFailDate != null) {
			timebasedOTPEntryCacheModel.lastFailDate = lastFailDate.getTime();
		}
		else {
			timebasedOTPEntryCacheModel.lastFailDate = Long.MIN_VALUE;
		}

		timebasedOTPEntryCacheModel.lastFailIP = getLastFailIP();

		String lastFailIP = timebasedOTPEntryCacheModel.lastFailIP;

		if ((lastFailIP != null) && (lastFailIP.length() == 0)) {
			timebasedOTPEntryCacheModel.lastFailIP = null;
		}

		Date lastSuccessDate = getLastSuccessDate();

		if (lastSuccessDate != null) {
			timebasedOTPEntryCacheModel.lastSuccessDate =
				lastSuccessDate.getTime();
		}
		else {
			timebasedOTPEntryCacheModel.lastSuccessDate = Long.MIN_VALUE;
		}

		timebasedOTPEntryCacheModel.lastSuccessIP = getLastSuccessIP();

		String lastSuccessIP = timebasedOTPEntryCacheModel.lastSuccessIP;

		if ((lastSuccessIP != null) && (lastSuccessIP.length() == 0)) {
			timebasedOTPEntryCacheModel.lastSuccessIP = null;
		}

		timebasedOTPEntryCacheModel.mfaCheckerName = getMfaCheckerName();

		String mfaCheckerName = timebasedOTPEntryCacheModel.mfaCheckerName;

		if ((mfaCheckerName != null) && (mfaCheckerName.length() == 0)) {
			timebasedOTPEntryCacheModel.mfaCheckerName = null;
		}

		timebasedOTPEntryCacheModel.sharedSecret = getSharedSecret();

		String sharedSecret = timebasedOTPEntryCacheModel.sharedSecret;

		if ((sharedSecret != null) && (sharedSecret.length() == 0)) {
			timebasedOTPEntryCacheModel.sharedSecret = null;
		}

		return timebasedOTPEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TimebasedOTPEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TimebasedOTPEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TimebasedOTPEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((TimebasedOTPEntry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<TimebasedOTPEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<TimebasedOTPEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TimebasedOTPEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((TimebasedOTPEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		TimebasedOTPEntry.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		TimebasedOTPEntry.class, ModelWrapper.class
	};
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _entryId;
	private long _companyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _failedAttempts;
	private Date _lastFailDate;
	private String _lastFailIP;
	private Date _lastSuccessDate;
	private String _lastSuccessIP;
	private String _mfaCheckerName;
	private String _originalMfaCheckerName;
	private String _sharedSecret;
	private long _columnBitmask;
	private TimebasedOTPEntry _escapedModel;

}