/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multi.factor.authentication.checker.timebased.otp.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.multi.factor.authentication.checker.timebased.otp.model.TimebasedOTPEntry;
import com.liferay.multi.factor.authentication.checker.timebased.otp.service.TimebasedOTPEntryLocalServiceUtil;

/**
 * The extended model base implementation for the TimebasedOTPEntry service. Represents a row in the &quot;MFATOTPEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TimebasedOTPEntryImpl}.
 * </p>
 *
 * @author arthurchan35
 * @see TimebasedOTPEntryImpl
 * @see TimebasedOTPEntry
 * @generated
 */
@ProviderType
public abstract class TimebasedOTPEntryBaseImpl
	extends TimebasedOTPEntryModelImpl implements TimebasedOTPEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a timebased otp entry model instance should use the <code>TimebasedOTPEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TimebasedOTPEntryLocalServiceUtil.addTimebasedOTPEntry(this);
		}
		else {
			TimebasedOTPEntryLocalServiceUtil.updateTimebasedOTPEntry(this);
		}
	}

}